<?php
/**
 * Uninstall routine for Simple WP MCP Adapter OAuth.
 *
 * @package SimpleWpMcpAdapterOAuth
 */

if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

global $wpdb;

$tables = array(
	$wpdb->prefix . 'simple_mcp_oauth_clients',
	$wpdb->prefix . 'simple_mcp_oauth_auth_codes',
	$wpdb->prefix . 'simple_mcp_oauth_refresh_tokens',
);

foreach ( $tables as $table ) {
	// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared -- Table names are generated by plugin-owned fixed suffixes.
	$wpdb->query( "DROP TABLE IF EXISTS {$table}" );
}

$upload_dir = wp_upload_dir();
$keys_dir   = trailingslashit( $upload_dir['basedir'] ) . 'simple-wp-mcp-adapter-oauth-keys';

$known_files = array(
	$keys_dir . '/private.key',
	$keys_dir . '/public.key',
	$keys_dir . '/.htaccess',
);

foreach ( $known_files as $file ) {
	if ( file_exists( $file ) ) {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.unlink_unlink
		unlink( $file );
	}
}

if ( is_dir( $keys_dir ) ) {
	$remaining_entries = array_diff( scandir( $keys_dir ), array( '.', '..' ) ); // phpcs:ignore WordPress.WP.AlternativeFunctions.directory_scan_scandir
	if ( empty( $remaining_entries ) ) {
		// phpcs:ignore WordPress.WP.AlternativeFunctions.file_system_operations_rmdir
		rmdir( $keys_dir );
	}
}
